services:
  fedora:
    build: .
    restart: unless-stopped
    environment:
        LANG: "C.UTF-8"
    volumes:
      - ./home/.cache/:/home/stephane/.cache/
      - ./home/.config/:/home/stephane/.config/
      - ./home/.local/:/home/stephane/.local/
      - /home/stephane/git/:/home/stephane/git/
